# Generated by Django 3.2.9 on 2021-11-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finalproject.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('user', models.ForeignKey(default=finalproject.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('emailId', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=finalproject.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('questionText', models.CharField(max_length=1000)),
                ('student', models.ForeignKey(default=finalproject.models.get_default_student, on_delete=django.db.models.deletion.CASCADE, to='finalproject.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=finalproject.models.get_default_question, on_delete=django.db.models.deletion.CASCADE, to='finalproject.question')),
                ('teacher', models.ForeignKey(default=finalproject.models.get_default_teacher, on_delete=django.db.models.deletion.CASCADE, to='finalproject.teacherinfo')),
            ],
        ),
    ]
