# Generated by Django 3.2.9 on 2021-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerText',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
