# Generated by Django 3.2.9 on 2021-11-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0002_answer_answertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionTitle',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
