# Generated by Django 3.2.9 on 2021-11-26 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_question_questiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='emailId',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='qualifications',
            field=models.CharField(default='ishita@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='questionTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='contactNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='emailId',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='contactNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
